// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	exec "os/exec"

	config "github.com/Oppodelldog/droxy/config"

	mock "github.com/stretchr/testify/mock"
)

// CommandBuilder is an autogenerated mock type for the CommandBuilder type
type CommandBuilder struct {
	mock.Mock
}

// BuildCommandFromConfig provides a mock function with given fields: cmdDef
func (_m *CommandBuilder) BuildCommandFromConfig(cmdDef config.CommandDefinition) (*exec.Cmd, error) {
	ret := _m.Called(cmdDef)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(config.CommandDefinition) *exec.Cmd); ok {
		r0 = rf(cmdDef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(config.CommandDefinition) error); ok {
		r1 = rf(cmdDef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
