// Code generated by mockery v1.0.0
package mocks

import (
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// CommandRunner is an autogenerated mock type for the CommandRunner type
type CommandRunner struct {
	mock.Mock
}

// RunCommand provides a mock function with given fields: _a0
func (_m *CommandRunner) RunCommand(_a0 *exec.Cmd) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*exec.Cmd) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
