// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	config "github.com/Oppodelldog/droxy/config"
	mock "github.com/stretchr/testify/mock"
)

// ConfigLoader is an autogenerated mock type for the ConfigLoader type
type ConfigLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *ConfigLoader) Load() config.Configuration {
	ret := _m.Called()

	var r0 config.Configuration
	if rf, ok := ret.Get(0).(func() config.Configuration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Configuration)
	}

	return r0
}

// NewConfigLoader creates a new instance of ConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigLoader {
	mock := &ConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
