// Code generated by mockery v1.0.0
package mocks

import (
	config "github.com/Oppodelldog/droxy/config"
	mock "github.com/stretchr/testify/mock"
)

// ConfigLoader is an autogenerated mock type for the ConfigLoader type
type ConfigLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *ConfigLoader) Load() *config.Configuration {
	ret := _m.Called()

	var r0 *config.Configuration
	if rf, ok := ret.Get(0).(func() *config.Configuration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Configuration)
		}
	}

	return r0
}
