// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExecutableNameParser is an autogenerated mock type for the ExecutableNameParser type
type ExecutableNameParser struct {
	mock.Mock
}

// ParseCommandNameFromCommandLine provides a mock function with given fields:
func (_m *ExecutableNameParser) ParseCommandNameFromCommandLine() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewExecutableNameParser creates a new instance of ExecutableNameParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutableNameParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutableNameParser {
	mock := &ExecutableNameParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
