// Code generated by mockery v1.0.0
package mocks

import "github.com/stretchr/testify/mock"

// ConfigLoader is an autogenerated mock type for the ConfigLoader type
type ProxyFilesCreator struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *ProxyFilesCreator) CreateProxyFiles(isForced bool) error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(isForced)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(error)
		}
	}

	return r0
}
